### ISSUE TITLE
Switch from `splode_message` to `message` and inject default implementation

### ISSUE THREAD

**Issue by zachallaun** [ash-project/splode#2]
[Discussion on ElixirForum](https://elixirforum.com/t/splode-aggregatable-and-consistent-errors-for-elixir/62313/7)

**Comment by jimsynz** [comment]
Closed by cd276643888733302ed1a235055a3af312aaba95

**Comment by zachdaniel** [comment]
we didn't inject a default implementation, so this is only half closed, but currently I don't have plans to create a default message (but PRs welcome)
